import type {
  AIInsight,
  ChartDataPoint,
  Customer,
  CustomerEvent,
  GlanceStat,
  KanbanColumn,
  NextBestAction,
  OperationalMetric,
  OpsCoverageMember,
  PriorityAccount,
  SLARisk,
  ThroughputEntry,
  Workflow,
} from "@/types";

const now = new Date();

function daysAgo(days: number): Date {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d;
}

function hoursAgo(hours: number): Date {
  const d = new Date(now);
  d.setHours(d.getHours() - hours);
  return d;
}

function minutesAgo(mins: number): Date {
  const d = new Date(now);
  d.setMinutes(d.getMinutes() - mins);
  return d;
}

export const customers: Customer[] = [
  {
    id: "cust_001",
    name: "Sarah Chen",
    company: "NovaTech Solutions",
    email: "sarah@novatech.io",
    stage: "onboarding",
    healthScore: 62,
    healthStatus: "watch",
    engagementScore: 58,
    mrr: 2400,
    daysInStage: 12,
    lastActive: hoursAgo(2),
    owner: "Alex Rivera",
    renewalDate: daysAgo(-340),
    featuresAdopted: 3,
    totalFeatures: 12,
  },
  {
    id: "cust_002",
    name: "Marcus Webb",
    company: "CloudScale Inc",
    email: "marcus@cloudscale.com",
    stage: "activation",
    healthScore: 78,
    healthStatus: "healthy",
    engagementScore: 82,
    mrr: 4800,
    daysInStage: 28,
    lastActive: hoursAgo(1),
    owner: "Jordan Lee",
    renewalDate: daysAgo(-280),
    featuresAdopted: 7,
    totalFeatures: 12,
  },
  {
    id: "cust_003",
    name: "Elena Rodriguez",
    company: "DataPulse Analytics",
    email: "elena@datapulse.co",
    stage: "adoption",
    healthScore: 91,
    healthStatus: "healthy",
    engagementScore: 88,
    mrr: 8200,
    daysInStage: 45,
    lastActive: minutesAgo(30),
    owner: "Alex Rivera",
    renewalDate: daysAgo(-120),
    featuresAdopted: 10,
    totalFeatures: 12,
  },
  {
    id: "cust_004",
    name: "James Park",
    company: "FinFlow Systems",
    email: "james@finflow.io",
    stage: "expansion",
    healthScore: 85,
    healthStatus: "healthy",
    engagementScore: 79,
    mrr: 12400,
    daysInStage: 60,
    lastActive: hoursAgo(4),
    owner: "Sam Patel",
    renewalDate: daysAgo(-90),
    featuresAdopted: 11,
    totalFeatures: 12,
  },
  {
    id: "cust_005",
    name: "Priya Sharma",
    company: "HealthBridge",
    email: "priya@healthbridge.com",
    stage: "renewal",
    healthScore: 72,
    healthStatus: "watch",
    engagementScore: 65,
    mrr: 9600,
    daysInStage: 15,
    lastActive: daysAgo(3),
    owner: "Jordan Lee",
    renewalDate: daysAgo(-25),
    featuresAdopted: 8,
    totalFeatures: 12,
  },
  {
    id: "cust_006",
    name: "David Okonkwo",
    company: "RetailEdge",
    email: "david@retailedge.com",
    stage: "at_risk",
    healthScore: 38,
    healthStatus: "critical",
    engagementScore: 22,
    mrr: 3200,
    daysInStage: 21,
    lastActive: daysAgo(14),
    owner: "Alex Rivera",
    renewalDate: daysAgo(-45),
    featuresAdopted: 2,
    totalFeatures: 12,
  },
  {
    id: "cust_007",
    name: "Lisa Thompson",
    company: "MediaStream Pro",
    email: "lisa@mediastream.pro",
    stage: "onboarding",
    healthScore: 55,
    healthStatus: "at_risk",
    engagementScore: 48,
    mrr: 1800,
    daysInStage: 18,
    lastActive: daysAgo(5),
    owner: "Sam Patel",
    renewalDate: daysAgo(-350),
    featuresAdopted: 2,
    totalFeatures: 12,
  },
  {
    id: "cust_008",
    name: "Ryan Foster",
    company: "LogiChain",
    email: "ryan@logichain.io",
    stage: "activation",
    healthScore: 83,
    healthStatus: "healthy",
    engagementScore: 76,
    mrr: 5600,
    daysInStage: 22,
    lastActive: hoursAgo(6),
    owner: "Jordan Lee",
    renewalDate: daysAgo(-300),
    featuresAdopted: 6,
    totalFeatures: 12,
  },
];

export const operationalMetrics: OperationalMetric[] = [
  { label: "Active Customers", value: 847, change: 4.2, trend: "up" },
  { label: "Onboarding Health", value: "78%", change: -2.1, trend: "down", status: "watch" },
  { label: "Avg Health Score", value: 74, change: 1.8, trend: "up" },
  { label: "At-Risk Accounts", value: 23, change: 12.5, trend: "up", status: "at_risk" },
  { label: "Renewal Pipeline", value: "$1.2M", change: 8.3, trend: "up" },
  { label: "SLA Compliance", value: "94%", change: -1.2, trend: "down", status: "watch" },
];

export const slaRisks: SLARisk[] = [
  { id: "sla_1", label: "Onboarding Completion", current: 78, threshold: 85, unit: "%", status: "watch" },
  { id: "sla_2", label: "First Response Time", current: 2.4, threshold: 4, unit: "hrs", status: "healthy" },
  { id: "sla_3", label: "Activation Rate (30d)", current: 62, threshold: 70, unit: "%", status: "at_risk" },
  { id: "sla_4", label: "Renewal Forecast Accuracy", current: 88, threshold: 90, unit: "%", status: "watch" },
];

export const lifecycleDistribution: ChartDataPoint[] = [
  { name: "Onboarding", value: 124 },
  { name: "Activation", value: 198 },
  { name: "Adoption", value: 312 },
  { name: "Expansion", value: 89 },
  { name: "Renewal", value: 67 },
  { name: "At Risk", value: 23 },
];

export const engagementTrend: ChartDataPoint[] = [
  { name: "Mon", value: 72, secondary: 68 },
  { name: "Tue", value: 74, secondary: 70 },
  { name: "Wed", value: 71, secondary: 69 },
  { name: "Thu", value: 76, secondary: 72 },
  { name: "Fri", value: 78, secondary: 74 },
  { name: "Sat", value: 65, secondary: 62 },
  { name: "Sun", value: 63, secondary: 60 },
];

export const onboardingFunnel: ChartDataPoint[] = [
  { name: "Signed Up", value: 100 },
  { name: "Profile Complete", value: 86 },
  { name: "First Integration", value: 72 },
  { name: "Team Invited", value: 58 },
  { name: "Feature Adopted", value: 45 },
  { name: "Activated", value: 38 },
];

export const aiInsights: AIInsight[] = [
  {
    id: "ins_001",
    title: "Onboarding bottleneck detected in week 2",
    summary:
      "34% of new accounts stall between profile completion and first integration. Average time-to-first-value increased 18% this month. Accounts without team invites within 7 days show 3.2x higher churn probability.",
    category: "onboarding",
    severity: "warning",
    confidence: 87,
    affectedCustomers: 42,
    recommendedAction: "Trigger accelerated onboarding sequence with dedicated CSM touchpoint",
    createdAt: hoursAgo(2),
  },
  {
    id: "ins_002",
    title: "Churn risk cluster in mid-market segment",
    summary:
      "8 accounts in the $3K–$5K MRR range show declining engagement patterns similar to historical churn cohorts. Feature adoption dropped below 25% threshold across analytics and reporting modules.",
    category: "churn",
    severity: "critical",
    confidence: 92,
    affectedCustomers: 8,
    recommendedAction: "Initiate retention playbook with executive sponsor outreach",
    createdAt: hoursAgo(4),
  },
  {
    id: "ins_003",
    title: "Expansion opportunity in enterprise tier",
    summary:
      "12 accounts exceed 90% feature utilization with consistent growth in API calls (+45% MoM). Usage patterns align with accounts that expanded within 60 days historically.",
    category: "expansion",
    severity: "opportunity",
    confidence: 79,
    affectedCustomers: 12,
    recommendedAction: "Deploy upsell campaign targeting power users with enterprise tier preview",
    createdAt: hoursAgo(6),
  },
  {
    id: "ins_004",
    title: "Support ticket volume spike correlates with release",
    summary:
      "Support tickets increased 67% following v3.2 release. Primary themes: API migration confusion and dashboard layout changes. Resolution time up 23%.",
    category: "workload",
    severity: "warning",
    confidence: 94,
    affectedCustomers: 156,
    recommendedAction: "Deploy in-app guidance tour and update knowledge base articles",
    createdAt: hoursAgo(8),
  },
  {
    id: "ins_005",
    title: "Renewal pipeline concentration risk",
    summary:
      "$340K in renewals concentrated in Q1 with 5 accounts showing declining NPS. Historical data suggests proactive engagement 60+ days before renewal improves close rate by 28%.",
    category: "renewal",
    severity: "warning",
    confidence: 85,
    affectedCustomers: 5,
    recommendedAction: "Schedule renewal strategy sessions for at-risk Q1 accounts",
    createdAt: daysAgo(1),
  },
];

export const nextBestActions: NextBestAction[] = [
  {
    id: "nba_001",
    title: "Escalate onboarding risk",
    description: "NovaTech Solutions stalled at integration step for 12 days. Assign dedicated CSM for white-glove onboarding.",
    priority: "high",
    type: "escalate",
    customerId: "cust_001",
    customerName: "NovaTech Solutions",
    estimatedImpact: "Prevent $28K ARR churn risk",
  },
  {
    id: "nba_002",
    title: "Trigger lifecycle nurture",
    description: "RetailEdge shows 14-day inactivity. Send re-engagement sequence with personalized feature recommendations.",
    priority: "high",
    type: "nurture",
    customerId: "cust_006",
    customerName: "RetailEdge",
    estimatedImpact: "Recover 38 health score",
  },
  {
    id: "nba_003",
    title: "Recommend customer outreach",
    description: "HealthBridge renewal in 25 days with declining engagement. Schedule executive business review.",
    priority: "medium",
    type: "outreach",
    customerId: "cust_005",
    customerName: "HealthBridge",
    estimatedImpact: "Secure $115K renewal",
  },
  {
    id: "nba_004",
    title: "Suggest upsell opportunity",
    description: "DataPulse Analytics at 83% feature adoption with growing API usage. Present enterprise tier capabilities.",
    priority: "medium",
    type: "upsell",
    customerId: "cust_003",
    customerName: "DataPulse Analytics",
    estimatedImpact: "+$4.8K MRR expansion",
  },
  {
    id: "nba_005",
    title: "Prioritize support intervention",
    description: "MediaStream Pro opened 3 tickets this week related to API migration. Proactive support call recommended.",
    priority: "medium",
    type: "support",
    customerId: "cust_007",
    customerName: "MediaStream Pro",
    estimatedImpact: "Improve NPS by 15 points",
  },
];

export const workflows: Workflow[] = [
  {
    id: "wf_001",
    name: "New Customer Onboarding",
    description: "Automated welcome sequence, setup reminders, and milestone celebrations via Braze",
    status: "active",
    stage: "onboarding",
    triggerCount: 1247,
    completionRate: 78,
    avgDuration: "14 days",
    lastTriggered: minutesAgo(12),
    dependencies: ["Snowflake: signup event", "Hightouch: audience sync"],
    aiRecommendation: "Add day-3 integration nudge — accounts receiving it activate 22% faster",
  },
  {
    id: "wf_002",
    name: "Activation Acceleration",
    description: "Feature adoption prompts and usage-based messaging for accounts in activation stage",
    status: "active",
    stage: "activation",
    triggerCount: 892,
    completionRate: 62,
    avgDuration: "21 days",
    lastTriggered: minutesAgo(45),
    dependencies: ["Snowflake: usage events", "Hightouch: engagement score"],
    aiRecommendation: "Split by company size — SMB responds better to in-app vs email",
  },
  {
    id: "wf_003",
    name: "Churn Risk Intervention",
    description: "Multi-channel retention sequence triggered by declining health scores",
    status: "active",
    stage: "at_risk",
    triggerCount: 156,
    completionRate: 45,
    avgDuration: "7 days",
    lastTriggered: hoursAgo(2),
    dependencies: ["Hightouch: churn-risk sync", "Braze: retention canvas"],
    aiRecommendation: "Escalate to CSM when health score drops below 40 within 48hrs",
  },
  {
    id: "wf_004",
    name: "Renewal Preparation",
    description: "90/60/30-day renewal reminders with value recap and expansion offers",
    status: "active",
    stage: "renewal",
    triggerCount: 234,
    completionRate: 88,
    avgDuration: "90 days",
    lastTriggered: hoursAgo(6),
    dependencies: ["Snowflake: contract dates", "Braze: renewal journey"],
  },
  {
    id: "wf_005",
    name: "Expansion Upsell",
    description: "Usage threshold triggers for tier upgrade and add-on recommendations",
    status: "paused",
    stage: "expansion",
    triggerCount: 67,
    completionRate: 34,
    avgDuration: "30 days",
    lastTriggered: daysAgo(3),
    dependencies: ["Snowflake: usage limits", "Hightouch: expansion score"],
    aiRecommendation: "Resume workflow — 12 accounts currently meet expansion criteria",
  },
  {
    id: "wf_006",
    name: "Support Escalation Path",
    description: "Auto-escalate high-priority tickets to CSM and account team",
    status: "active",
    stage: "adoption",
    triggerCount: 445,
    completionRate: 91,
    avgDuration: "4 hrs",
    lastTriggered: minutesAgo(8),
    dependencies: ["Zendesk: ticket events", "Slack: team notification"],
  },
];

export const customerEvents: CustomerEvent[] = [
  {
    id: "evt_001",
    customerId: "cust_003",
    customerName: "Elena Rodriguez",
    company: "DataPulse Analytics",
    type: "product_usage",
    title: "API calls exceeded 50K threshold",
    description: "Daily API volume reached 52,340 calls — 45% above 30-day average",
    timestamp: minutesAgo(2),
    severity: "low",
    metadata: { apiCalls: 52340, threshold: 50000 },
  },
  {
    id: "evt_002",
    customerId: "cust_006",
    customerName: "David Okonkwo",
    company: "RetailEdge",
    type: "inactivity",
    title: "14-day inactivity detected",
    description: "No product logins or API activity in 14 days. Health score dropped to 38.",
    timestamp: minutesAgo(15),
    severity: "high",
  },
  {
    id: "evt_003",
    customerId: "cust_002",
    customerName: "Marcus Webb",
    company: "CloudScale Inc",
    type: "feature_engagement",
    title: "Advanced analytics module activated",
    description: "Team enabled custom dashboards and scheduled reports",
    timestamp: minutesAgo(28),
    severity: "low",
  },
  {
    id: "evt_004",
    customerId: "cust_007",
    customerName: "Lisa Thompson",
    company: "MediaStream Pro",
    type: "support_ticket",
    title: "Support ticket #4821 created",
    description: "API migration assistance requested — Priority: High",
    timestamp: minutesAgo(35),
    severity: "medium",
  },
  {
    id: "evt_005",
    customerId: "cust_004",
    customerName: "James Park",
    company: "FinFlow Systems",
    type: "subscription_upgrade",
    title: "Upgraded to Enterprise tier",
    description: "MRR increased from $8,200 to $12,400 (+51%)",
    timestamp: hoursAgo(1),
    severity: "low",
    metadata: { previousMrr: 8200, newMrr: 12400 },
  },
  {
    id: "evt_006",
    customerId: "cust_001",
    customerName: "Sarah Chen",
    company: "NovaTech Solutions",
    type: "churn_signal",
    title: "Onboarding milestone missed",
    description: "Account failed to complete first integration within 14-day SLA",
    timestamp: hoursAgo(2),
    severity: "high",
  },
  {
    id: "evt_007",
    customerId: "cust_008",
    customerName: "Ryan Foster",
    company: "LogiChain",
    type: "onboarding_complete",
    title: "Onboarding checklist completed",
    description: "All 8 onboarding milestones achieved in 18 days",
    timestamp: hoursAgo(3),
    severity: "low",
  },
  {
    id: "evt_008",
    customerId: "cust_005",
    customerName: "Priya Sharma",
    company: "HealthBridge",
    type: "campaign_sent",
    title: "Renewal nurture email delivered",
    description: "60-day renewal reminder sent via Braze lifecycle canvas",
    timestamp: hoursAgo(4),
    severity: "low",
  },
  {
    id: "evt_009",
    customerId: "cust_003",
    customerName: "Elena Rodriguez",
    company: "DataPulse Analytics",
    type: "feature_engagement",
    title: "New team member invited",
    description: "3 additional seats activated — team size now 12",
    timestamp: hoursAgo(5),
    severity: "low",
  },
  {
    id: "evt_010",
    customerId: "cust_006",
    customerName: "David Okonkwo",
    company: "RetailEdge",
    type: "churn_signal",
    title: "NPS detractor response",
    description: "Customer rated product 4/10 citing integration complexity",
    timestamp: hoursAgo(8),
    severity: "high",
  },
];

export const stackIntegrations = [
  { name: "Snowflake", role: "Data Warehouse", status: "connected" as const, latency: "12ms" },
  { name: "Hightouch", role: "Reverse ETL", status: "connected" as const, latency: "340ms" },
  { name: "Braze", role: "Engagement", status: "connected" as const, latency: "89ms" },
  { name: "Pulse-Ops AI", role: "Application", status: "connected" as const, latency: "Operational" },
];

export const todayAtAGlance: GlanceStat[] = [
  {
    id: "at_risk",
    label: "At-Risk Accounts",
    value: 23,
    change: 12.5,
    trend: [14, 16, 17, 19, 20, 21, 23],
    status: "at_risk",
    targetSection: "section-priority",
  },
  {
    id: "sla",
    label: "SLA Breaches",
    value: 4,
    change: -8.2,
    trend: [7, 6, 6, 5, 5, 4, 4],
    status: "watch",
    targetSection: "section-sla",
  },
  {
    id: "workflows",
    label: "Open Workflows",
    value: 10,
    change: 3.1,
    trend: [6, 7, 8, 8, 9, 9, 10],
    targetSection: "section-kanban",
  },
  {
    id: "actions",
    label: "AI Actions Queued",
    value: 5,
    change: 0,
    trend: [3, 4, 4, 5, 5, 5, 5],
    status: "watch",
    targetSection: "section-actions",
  },
  {
    id: "health",
    label: "Lifecycle Health",
    value: "78%",
    change: -2.1,
    trend: [82, 81, 80, 79, 79, 78, 78],
    status: "watch",
    targetSection: "section-lifecycle",
  },
];

export const inflowResolvedWeekly: ChartDataPoint[] = [
  { name: "Mon", value: 142, secondary: 118 },
  { name: "Tue", value: 156, secondary: 134 },
  { name: "Wed", value: 148, secondary: 141 },
  { name: "Thu", value: 167, secondary: 152 },
  { name: "Fri", value: 134, secondary: 128 },
  { name: "Sat", value: 89, secondary: 94 },
  { name: "Sun", value: 76, secondary: 81 },
];

export const kanbanSnapshot: KanbanColumn[] = [
  {
    id: "onboarding",
    title: "Onboarding",
    items: [
      { id: "k1", company: "NovaTech Solutions", healthScore: 62, healthStatus: "watch", owner: "Alex Rivera", label: "Integration stalled" },
      { id: "k2", company: "MediaStream Pro", healthScore: 55, healthStatus: "at_risk", owner: "Sam Patel", label: "Day 18 — no team invite" },
      { id: "k3", company: "BrightPath CRM", healthScore: 71, healthStatus: "healthy", owner: "Jordan Lee" },
    ],
  },
  {
    id: "activation",
    title: "Activation",
    items: [
      { id: "k4", company: "CloudScale Inc", healthScore: 78, healthStatus: "healthy", owner: "Jordan Lee" },
      { id: "k5", company: "LogiChain", healthScore: 83, healthStatus: "healthy", owner: "Jordan Lee" },
    ],
  },
  {
    id: "adoption",
    title: "Adoption",
    items: [
      { id: "k6", company: "DataPulse Analytics", healthScore: 91, healthStatus: "healthy", owner: "Alex Rivera", label: "Power user" },
      { id: "k7", company: "SyncWave", healthScore: 86, healthStatus: "healthy", owner: "Sam Patel" },
    ],
  },
  {
    id: "renewal",
    title: "Renewal",
    items: [
      { id: "k8", company: "HealthBridge", healthScore: 72, healthStatus: "watch", owner: "Jordan Lee", label: "Renewal in 25d" },
    ],
  },
  {
    id: "at_risk",
    title: "Intervention",
    items: [
      { id: "k9", company: "RetailEdge", healthScore: 38, healthStatus: "critical", owner: "Alex Rivera", label: "14d inactive" },
    ],
  },
];

export const opsCoverage: OpsCoverageMember[] = [
  { id: "ops_1", name: "Alex Rivera", role: "Lifecycle Ops", accountsOwned: 142, atRiskCount: 8, actionsToday: 4, status: "focused", note: "Retention playbook active" },
  { id: "ops_2", name: "Jordan Lee", role: "Lifecycle Ops", accountsOwned: 128, atRiskCount: 3, actionsToday: 2, status: "available" },
  { id: "ops_3", name: "Sam Patel", role: "Lifecycle Ops", accountsOwned: 119, atRiskCount: 6, actionsToday: 5, status: "at_capacity", note: "Onboarding surge" },
  { id: "ops_4", name: "Taylor Kim", role: "Expansion Ops", accountsOwned: 96, atRiskCount: 1, actionsToday: 1, status: "available" },
];

export const priorityAccounts: PriorityAccount[] = [
  { id: "p1", company: "RetailEdge", reason: "14-day inactivity · NPS detractor", healthScore: 38, healthStatus: "critical", owner: "Alex Rivera", mrr: 3200, urgency: "critical" },
  { id: "p2", company: "NovaTech Solutions", reason: "Onboarding milestone missed", healthScore: 62, healthStatus: "watch", owner: "Alex Rivera", mrr: 2400, urgency: "high" },
  { id: "p3", company: "MediaStream Pro", reason: "3 support escalations this week", healthScore: 55, healthStatus: "at_risk", owner: "Sam Patel", mrr: 1800, urgency: "high" },
  { id: "p4", company: "HealthBridge", reason: "Renewal in 25 days · declining engagement", healthScore: 72, healthStatus: "watch", owner: "Jordan Lee", mrr: 9600, urgency: "high" },
  { id: "p5", company: "FinFlow Systems", reason: "Expansion opportunity · 90% feature adoption", healthScore: 85, healthStatus: "healthy", owner: "Sam Patel", mrr: 12400, urgency: "medium" },
  { id: "p6", company: "CloudScale Inc", reason: "Activation milestone due in 3 days", healthScore: 78, healthStatus: "healthy", owner: "Jordan Lee", mrr: 4800, urgency: "medium" },
];

export const throughputLeaderboard: ThroughputEntry[] = [
  { id: "t1", name: "Jordan Lee", role: "Lifecycle Ops", lastWeek: 34, trend: [22, 26, 28, 30, 29, 31, 33, 34] },
  { id: "t2", name: "Alex Rivera", role: "Lifecycle Ops", lastWeek: 31, trend: [24, 25, 27, 28, 29, 30, 28, 31] },
  { id: "t3", name: "Sam Patel", role: "Lifecycle Ops", lastWeek: 28, trend: [20, 22, 24, 23, 25, 26, 27, 28] },
  { id: "t4", name: "Taylor Kim", role: "Expansion Ops", lastWeek: 19, trend: [12, 14, 15, 16, 17, 18, 17, 19] },
];
